packages:
  - templates/*
  - templates/*/*
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@oas-ui/core@2.2.2 || 2.2.3 || 2.2.4 || 2.2.5 || 2.2.6'
  - '@oas-ui/i18n@2.2.2 || 2.2.3 || 2.2.4 || 2.2.5 || 2.2.6'
  - '@oas-ui/icons@2.2.2 || 2.2.3 || 2.2.4 || 2.2.5 || 2.2.6'
  - '@oas-ui/theme@2.2.2 || 2.2.3 || 2.2.4 || 2.2.5 || 2.2.6'
  - '@oas-ui/ui@2.2.2 || 2.2.3 || 2.2.4 || 2.2.5 || 2.2.6'
