packages:
  - templates/*
  - templates/*/*
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@oas-ui/core'
  - '@oas-ui/i18n'
  - '@oas-ui/icons'
  - '@oas-ui/theme'
  - '@oas-ui/ui'
